---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Grace Lee and Jiyun Hyo"
date: ""
output: pdf_document

---

```{r libraries}
library(dplyr)
library(tidyverse)
library(sf)
library(viridis)
library(ggspatial) #for scale annotation
```


```{r read_in_data, , echo=FALSE}
data <- read.csv(file = '../data/COVID_raw_12.8.csv')
tidy_data <- select(data, c('Participant_ID', 'age',"usres", "state", "race", "sex", "localsip", "localsip2", "localsip3", "leavehomeact___1", "leavehomeact___2", "leavehomeact___3", "leavehomeact___4", "leavehomeact___5", "leavehomeact___6", "leavehomeact___7", "leavehomereason___1", "leavehomereason___2", "leavehomereason___3", "leavehomereason___4", "leavehomereason___5", "leavehomereason___6", "leavehomereason___7", "localsiphours", "covidsick", "hhcovidsick", "ffcovidsick", "Classification", "covidtest", "educ", "hhincome"))
tidy_data$race[is.na(tidy_data$race) == TRUE] <- "6"
number_of_hours <- tidy_data %>%
  group_by(race) %>%
 # summarize(localsiphours) %>%
  summarise_at(vars(localsiphours), list(hours = mean),na.rm = TRUE) %>% #to summarize count
  print()



number_of_hours$race[number_of_hours$race == 0] <- "American Indian"
number_of_hours$race[number_of_hours$race == 1] <- "Asian"
number_of_hours$race[number_of_hours$race == 2] <- "Native Hawaiian"
number_of_hours$race[number_of_hours$race == 3] <- "Black"
number_of_hours$race[number_of_hours$race == 4] <- "White"
number_of_hours$race[number_of_hours$race == 5] <- "Mixed"
number_of_hours$race[number_of_hours$race == 6] <- "Unknown"

ggplot(data=number_of_hours, aes(x=race, y=hours)) +
  geom_bar(stat="identity") +
  labs (
    y = "Number of Hours Remained at Home",
    x = "Race",
    title = "Number of Hours Remained at Home by Race",
    ) 

glimpse(data)
glimpse(tidy_data)
summary(tidy_data)
```